// src/styles/theme.ts - FlowDeck Premium Educational Theme
// Palette inspired by Vedantu / Duolingo - light, warm, professional
export const theme = {
  colors: {
    background: '#F3F4F6',
    backgroundAlt: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceAlt: '#F9FAFB',
    cardBackground: '#FFFFFF',
    cardBorder: '#E5E7EB',
    primary: '#FF6B35',
    primaryDark: '#E85A24',
    primaryLight: '#FFF0EB',
    primaryGlow: 'rgba(255,107,53,0.15)',
    accent: '#00A896',
    accentDark: '#007A6D',
    accentLight: '#E6F7F5',
    accentGlow: 'rgba(0,168,150,0.15)',
    success: '#10B981',
    successBg: '#ECFDF5',
    danger: '#EF4444',
    dangerBg: '#FEF2F2',
    warning: '#F59E0B',
    warningBg: '#FFFBEB',
    textPrimary: '#1F2937',
    textSecondary: '#4B5563',
    textMuted: '#9CA3AF',
    textAccent: '#FF6B35',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#FFFFFF',
    tabActive: '#FF6B35',
    tabInactive: '#9CA3AF',
    tabBackground: '#FFFFFF',
    tabBorder: '#F3F4F6',
    white: '#FFFFFF',
    black: '#000000',
    overlay: 'rgba(17,24,39,0.45)',
    glassBg: 'rgba(255,255,255,0.95)',
    glassBorder: 'rgba(229,231,235,0.9)',
    separator: '#F3F4F6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 6,
    sm: 10,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    full: 999,
  },
  typography: {
    hero:     { fontSize: 32, fontWeight: '900' as const, letterSpacing: -0.8, color: '#1F2937' },
    h1:       { fontSize: 24, fontWeight: '800' as const, letterSpacing: -0.5, color: '#1F2937' },
    h2:       { fontSize: 20, fontWeight: '700' as const, color: '#1F2937' },
    h3:       { fontSize: 17, fontWeight: '700' as const, color: '#1F2937' },
    h4:       { fontSize: 15, fontWeight: '700' as const, color: '#1F2937' },
    body:     { fontSize: 15, fontWeight: '400' as const, lineHeight: 22, color: '#4B5563' },
    bodyBold: { fontSize: 15, fontWeight: '600' as const, lineHeight: 22, color: '#1F2937' },
    caption:  { fontSize: 12, fontWeight: '500' as const, lineHeight: 16, color: '#9CA3AF' },
    label:    { fontSize: 11, fontWeight: '700' as const, letterSpacing: 0.8, textTransform: 'uppercase' as const, color: '#9CA3AF' },
  },
  shadows: {
    xs: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.10,
      shadowRadius: 16,
      elevation: 8,
    },
    primary: {
      shadowColor: '#FF6B35',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.30,
      shadowRadius: 10,
      elevation: 5,
    },
    accent: {
      shadowColor: '#00A896',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 5,
    },
    glow: {
      shadowColor: '#FF6B35',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 4,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.07,
      shadowRadius: 6,
      elevation: 3,
    },
  },
};